# Generated by Django 5.2.4 on 2025-07-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_dailysalessummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
