# Generated by Django 5.2.4 on 2025-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nif',
            field=models.CharField(default=0, max_length=9, unique=True, verbose_name='NIF'),
            preserve_default=False,
        ),
    ]
