# Generated by Django 5.2.4 on 2025-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_customer_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
