# Generated by Django 5.2.4 on 2025-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_supplier_email_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='Model or version number', max_length=100, null=True),
        ),
    ]
