# Generated by Django 5.2.4 on 2025-08-14 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_arinvoice_aritem_arpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arpayment',
            name='date',
        ),
        migrations.AddField(
            model_name='arpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
