# Generated by Django 5.2.4 on 2026-04-09 15:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_brand_and_series(apps, schema_editor):
    Product = apps.get_model('stock', 'Product')
    Brand = apps.get_model('stock', 'Brand')
    ProductSeries = apps.get_model('stock', 'ProductSeries')

    brand_cache = {}

    for brand_name in Product.objects.order_by().values_list('brand', flat=True).distinct():
        cleaned = (brand_name or '').strip()
        if not cleaned:
            continue
        brand_obj, _created = Brand.objects.get_or_create(name=cleaned)
        brand_cache[cleaned] = brand_obj

    for product in Product.objects.all().iterator():
        brand_name = (product.brand or '').strip()
        model_name = (product.model or '').strip()
        update_fields = []

        brand_obj = brand_cache.get(brand_name)
        if brand_obj and product.brand_master_id != brand_obj.id:
            product.brand_master_id = brand_obj.id
            update_fields.append('brand_master')

        if brand_obj and model_name:
            series_obj, _created = ProductSeries.objects.get_or_create(
                brand_id=brand_obj.id,
                name=model_name,
            )
            if product.series_master_id != series_obj.id:
                product.series_master_id = series_obj.id
                update_fields.append('series_master')

        if update_fields:
            product.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_remove_arpayment_date_arpayment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.brand'),
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='stock.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='series_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.productseries'),
        ),
        migrations.AddConstraint(
            model_name='productseries',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_series_per_brand'),
        ),
        migrations.RunPython(backfill_brand_and_series, migrations.RunPython.noop),
    ]
