# Generated by Django 5.2.4 on 2026-04-09 16:24

from django.db import migrations, models


def backfill_brand_categories(apps, schema_editor):
    Brand = apps.get_model('stock', 'Brand')
    Product = apps.get_model('stock', 'Product')

    for brand in Brand.objects.all().iterator():
        category_ids = (
            Product.objects
            .filter(brand_master_id=brand.id, category__isnull=False)
            .order_by()
            .values_list('category_id', flat=True)
            .distinct()
        )
        if category_ids:
            brand.categories.add(*category_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_brand_product_color_product_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='stock.category'),
        ),
        migrations.RunPython(backfill_brand_categories, migrations.RunPython.noop),
    ]
