# Generated by Django 5.2.4 on 2026-04-10 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_saleorderchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('clock_out_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in_at', '-id'],
                'indexes': [models.Index(fields=['user', 'clock_in_at'], name='stock_atten_user_id_cb49d3_idx'), models.Index(fields=['user', 'clock_out_at'], name='stock_atten_user_id_fafa5b_idx')],
            },
        ),
    ]
