# Generated by Django 5.2.4 on 2026-04-12 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_printprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='received_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='status',
            field=models.CharField(choices=[('pending_receipt', 'Pending receipt'), ('received', 'Received')], db_index=True, default='received', max_length=20),
        ),
        migrations.CreateModel(
            name='InboundPendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='stock.inboundorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
