# Generated by Django 5.2.4 on 2026-07-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_seed_default_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printprofile',
            options={'verbose_name': 'Print profile', 'verbose_name_plural': 'Print profiles'},
        ),
        migrations.AddField(
            model_name='printprofile',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_profile', to='stock.store'),
        ),
    ]
