# Generated by Django 5.2.4 on 2026-07-13 13:26

import stock.models.catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_seed_store_print_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=stock.models.catalog.product_image_upload_to),
        ),
    ]
