# Generated by Django 5.2.4 on 2026-07-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='affects_stock',
            field=models.BooleanField(default=True),
        ),
    ]
