# Generated by Django 5.2.4 on 2026-07-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_saleorder_affects_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_locked',
            field=models.BooleanField(default=False),
        ),
    ]
