# Generated by Django 5.2.4 on 2026-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_product_price_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], db_index=True, default='', max_length=10),
        ),
    ]
