# Generated by Django 5.2.4 on 2026-08-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_basis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
