# Generated by Django 5.2.4 on 2026-08-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_alter_product_options_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('short', models.CharField(blank=True, default='', max_length=12)),
                ('shopify_tag', models.CharField(blank=True, default='', max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FragranceFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('shopify_tag', models.CharField(blank=True, default='', max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'fragrance families',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.concentration'),
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_families',
            field=models.ManyToManyField(blank=True, related_name='products', to='stock.fragrancefamily'),
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['house', 'name'],
                'constraints': [models.UniqueConstraint(fields=('house', 'name'), name='unique_inspiration')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='inspired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.inspiration'),
        ),
    ]
