# Generated by Django 5.2.4 on 2026-08-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_concentration_fragrancefamily_product_volume_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sellable_categories',
            field=models.ManyToManyField(blank=True, related_name='stores', to='stock.category'),
        ),
    ]
