# Generated by Django 5.2.4 on 2026-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_scentory_sells_perfume_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
