# Generated by Django 5.2.4 on 2026-08-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_product_barcode_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sync_to_shopify',
            field=models.BooleanField(default=True),
        ),
    ]
