# Generated by Django 5.2.4 on 2026-08-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_accessories_offline_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='universal_fit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility_groups',
            field=models.ManyToManyField(blank=True, related_name='products', to='stock.compatibilitygroup'),
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('normalised', models.CharField(db_index=True, editable=False, max_length=80)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='stock.brand')),
            ],
            options={
                'ordering': ['brand__name', '-release_year', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='compatibilitygroup',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='compatibility_groups', to='stock.devicemodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='device_models',
            field=models.ManyToManyField(blank=True, related_name='products', to='stock.devicemodel'),
        ),
        migrations.CreateModel(
            name='DeviceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=80)),
                ('normalised', models.CharField(db_index=True, editable=False, max_length=80)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='stock.devicemodel')),
            ],
            options={
                'verbose_name_plural': 'device aliases',
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('normalised',), name='unique_device_alias')],
            },
        ),
    ]
