# Generated by Django 5.2.4 on 2026-08-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_compatibilitygroup_product_universal_fit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.SlugField(max_length=40)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('number', 'Number'), ('boolean', 'Yes / No')], default='text', max_length=10)),
                ('unit', models.CharField(blank=True, help_text='e.g. mm, W, cm', max_length=12)),
                ('required', models.BooleanField(default=False)),
                ('variant_attribute', models.BooleanField(default=False)),
                ('show_in_list', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='stock.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stock.categoryattribute')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('attribute', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=200)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='stock.categoryattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='stock.product')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='values', to='stock.attributeoption')),
            ],
            options={
                'ordering': ['attribute__sort_order', 'attribute__name'],
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
