# Generated by Django 5.2.4 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_categoryattribute_attributeoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='form_kind',
            field=models.CharField(choices=[('general', 'General'), ('perfume', 'Perfume'), ('accessory', 'Accessory / device')], default='general', max_length=12),
        ),
    ]
