# Generated by Django 5.2.4 on 2026-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_seed_category_form_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='placed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
