# Generated by Django 5.2.4 on 2026-08-26 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_backfill_placed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShelfColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('swatch', models.CharField(blank=True, help_text='e.g. #1f2937', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ['brand__name', 'sort_key', 'name']},
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='sort_key',
            field=models.CharField(db_index=True, default='', editable=False, max_length=160),
        ),
        migrations.CreateModel(
            name='ModelShelfNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=120)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_notes', to='stock.devicemodel')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_notes', to='stock.casestyle')),
            ],
            options={
                'unique_together': {('style', 'model')},
            },
        ),
        migrations.CreateModel(
            name='CaseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('out', 'Out of stock'), ('display', 'On shelf'), ('extra', 'On shelf + extra above')], db_index=True, default='out', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_stock', to='stock.devicemodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_rows', to='stock.casestyle')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_stock', to='stock.shelfcolour')),
            ],
            options={
                'ordering': ['model', 'colour'],
                'unique_together': {('style', 'model', 'colour')},
            },
        ),
    ]
