# Generated by Django 5.2.4 on 2026-08-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_shelf_axis_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfstyle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_styles', to='stock.category'),
        ),
        migrations.AlterField(
            model_name='shelfstock',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_stock', to='stock.devicemodel'),
        ),
        migrations.AlterField(
            model_name='shelfstock',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_stock', to='stock.shelfoption'),
        ),
    ]
