# Generated by Django 5.2.4 on 2026-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0052_shelfstyle_category_alter_shelfstock_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfstyle',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
