# Generated by Django 5.2.4 on 2026-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0053_shelfstyle_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inspired_by_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_base',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_heart',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_top',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
