# Generated by Django 5.2.4 on 2026-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0054_product_inspired_by_text_product_notes_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
