# Generated by Django 5.2.4 on 2026-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0057_customer_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
    ]
