"""
Django settings for inventory_system project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ofv45l88dauyb%kza&q&j57k@9rm8o!5j1zs4ol#4ph(-@74q='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# 尝试自动添加本机局域网 IP（用于手机访问）
try:
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    ALLOWED_HOSTS.append(local_ip)
except:
    pass


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "stock.apps.StockConfig",
    "widget_tweaks",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inventory_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'stock.context_processors.store_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Lisbon'  # 正确设置为葡萄牙时区
USE_TZ = True  

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 登录后跳转到 dashboard
LOGIN_REDIRECT_URL = '/dashboard/'
# 未登录访问受保护页面时，跳转到 login
LOGIN_URL = '/login/'


# ---------------------------------------------------------------------------
# Shopify sync (product images -> Shopify store)
# Credentials come from the environment; never commit the token.
#   SHOPIFY_STORE_DOMAIN   e.g. 66tcd5-su.myshopify.com  (the *.myshopify.com admin domain)
#   SHOPIFY_ADMIN_TOKEN    Admin API access token from a custom app (shpat_...)
#   SHOPIFY_API_VERSION    Admin API version (default below)
#   SHOPIFY_AUTO_SYNC      "1" to auto-push a product's image to Shopify when it is
#                          uploaded in the app (off by default so dev/tests never call out).
# ---------------------------------------------------------------------------
SHOPIFY_STORE_DOMAIN = os.environ.get('SHOPIFY_STORE_DOMAIN', '66tcd5-su.myshopify.com')
SHOPIFY_ADMIN_TOKEN = os.environ.get('SHOPIFY_ADMIN_TOKEN', '')
SHOPIFY_API_VERSION = os.environ.get('SHOPIFY_API_VERSION', '2025-01')
SHOPIFY_AUTO_SYNC = os.environ.get('SHOPIFY_AUTO_SYNC', '') in {'1', 'true', 'True', 'yes', 'on'}
# When auto-sync is on, also CREATE the product in Shopify if it doesn't exist yet
# (otherwise only attach images to products already there).
SHOPIFY_AUTO_CREATE = os.environ.get('SHOPIFY_AUTO_CREATE', '') in {'1', 'true', 'True', 'yes', 'on'}
# Status for products the sync creates. DRAFT (default) so new products are
# reviewed before going live; set to ACTIVE to publish immediately.
SHOPIFY_NEW_PRODUCT_STATUS = os.environ.get('SHOPIFY_NEW_PRODUCT_STATUS', 'DRAFT').upper()