"""
Django settings for inventory_system project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load KEY=VALUE lines from a local .env (git-ignored) into the environment, so
# local secrets/toggles (e.g. Cloudinary) apply on every server start without
# having to export them each time. Real environment variables still win.
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _key, _value = _line.split('=', 1)
            os.environ.setdefault(_key.strip(), _value.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY / DEBUG come from the environment (.env, loaded above). The old
# hardcoded key is in the public git history and must be treated as leaked; the
# real key now lives only in .env (git-ignored). The fallback below is a
# non-production dev key, used only when .env is absent (e.g. a fresh checkout).
SECRET_KEY = os.environ.get('SECRET_KEY') or 'django-insecure-dev-only-not-for-production'

# Off by default (safe). .env sets DEBUG=True for local use; set it to False when
# the app is exposed on a public URL (then run `collectstatic` so WhiteNoise can
# serve static files).
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# 自动添加本机局域网 IP（用于手机/局域网访问）。用 UDP 路由探测法而非
# gethostbyname —— 后者在多网卡机器上（例如装了 Tailscale 之后）常返回错误的
# 169.254.x 链路本地地址，导致真实局域网 IP 触发 DisallowedHost。
def _detect_lan_ip():
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as _sk:
            _sk.connect(("8.8.8.8", 80))  # 不发数据，只取默认路由所用的本机 IP
            return _sk.getsockname()[0]
    except Exception:
        return None

_lan_ip = _detect_lan_ip()
if _lan_ip and _lan_ip not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_lan_ip)

# Extra hosts / CSRF origins from the environment (comma-separated), for when the
# app is reached through a tunnel domain — config-only, no code change:
#   ALLOWED_HOSTS=pos.example.com
#   CSRF_TRUSTED_ORIGINS=https://pos.example.com
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "stock.apps.StockConfig",
    "widget_tweaks",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves static files when DEBUG=False (runserver stops doing so). Must sit
    # right after SecurityMiddleware. Harmless when DEBUG=True.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inventory_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'stock.context_processors.store_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Lisbon'  # 正确设置为葡萄牙时区
USE_TZ = True  

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]
# collectstatic target; WhiteNoise serves from here when DEBUG=False.
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 登录后跳转到 dashboard
LOGIN_REDIRECT_URL = '/dashboard/'
# 未登录访问受保护页面时，跳转到 login
LOGIN_URL = '/login/'


# ---------------------------------------------------------------------------
# Shopify sync (product images -> Shopify store)
# Credentials come from the environment; never commit the token.
#   SHOPIFY_STORE_DOMAIN   e.g. 66tcd5-su.myshopify.com  (the *.myshopify.com admin domain)
#   SHOPIFY_ADMIN_TOKEN    Admin API access token from a custom app (shpat_...)
#   SHOPIFY_API_VERSION    Admin API version (default below)
#   SHOPIFY_AUTO_SYNC      "1" to auto-push a product's image to Shopify when it is
#                          uploaded in the app (off by default so dev/tests never call out).
# ---------------------------------------------------------------------------
SHOPIFY_STORE_DOMAIN = os.environ.get('SHOPIFY_STORE_DOMAIN', '66tcd5-su.myshopify.com')
SHOPIFY_ADMIN_TOKEN = os.environ.get('SHOPIFY_ADMIN_TOKEN', '')
SHOPIFY_API_VERSION = os.environ.get('SHOPIFY_API_VERSION', '2025-01')
SHOPIFY_AUTO_SYNC = os.environ.get('SHOPIFY_AUTO_SYNC', '') in {'1', 'true', 'True', 'yes', 'on'}
# When auto-sync is on, also CREATE the product in Shopify if it doesn't exist yet
# (otherwise only attach images to products already there).
SHOPIFY_AUTO_CREATE = os.environ.get('SHOPIFY_AUTO_CREATE', '') in {'1', 'true', 'True', 'yes', 'on'}
# Status for products the sync creates. DRAFT (default) so new products are
# reviewed before going live; set to ACTIVE to publish immediately.
SHOPIFY_NEW_PRODUCT_STATUS = os.environ.get('SHOPIFY_NEW_PRODUCT_STATUS', 'DRAFT').upper()

# --- Cloudinary (product image mirror) ---
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', 'bulvpmzg')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '')
CLOUDINARY_FOLDER = os.environ.get('CLOUDINARY_FOLDER', 'product_images')
CLOUDINARY_AUTO_SYNC = os.environ.get('CLOUDINARY_AUTO_SYNC', '') in {'1', 'true', 'True', 'yes', 'on'}